"""init

Revision ID: 19a6b48e1f94
Revises: 
Create Date: 2020-07-09 09:20:54.052158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19a6b48e1f94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['user_groups.group'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
