"""unique email

Revision ID: 880f9250619d
Revises: 
Create Date: 2020-09-10 19:30:18.138872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880f9250619d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_1', sa.String(), nullable=True),
    sa.Column('match_2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_1'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['match_2'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchs')
    op.drop_table('pets')
    op.drop_table('users')
    # ### end Alembic commands ###
